### ISSUE TITLE
Error when opening eshell

### ISSUE THREAD

**Issue by dakling** [kiennq/emacs-mini-modeline#25]
Hi,

on emacs 27.0.90, opening eshell while mini-modeline-mode is enabled leads to the error
`wrong type argument listp, " "`
This seems to be caused by the mode-line-format being set to " " under some circumstances:
```
(defun mini-modeline--enable ()
  "Enable 'mini-modeline'."
  ;; Hide modeline for terminal, or use empty modeline for GUI.
  (if (display-graphic-p)
      (setq-default mode-line-format " ")
    (setq-default mode-line-format nil))
...
```

When I change this to
```
(defun mini-modeline--enable ()
  "Enable 'mini-modeline'."
  ;; Hide modeline for terminal, or use empty modeline for GUI.
  (if (display-graphic-p)
      (setq-default mode-line-format nil)
    (setq-default mode-line-format nil))
...
```
things work fine (I am aware that the if-clause is not needed now, but I wanted to keep it close to the original code).

Is this related to the emacs version? Does the suggested fix make sense in general?

**Comment by kiennq** [comment]
> on emacs 27.0.90, opening eshell while mini-modeline-mode is enabled leads to the error
> `wrong type argument listp, " "`

This is because of `eshell-mode` will try to use `memq` on `mode-line-format`, which is not list.

Your suggested fix looks fine. Just one thing, we need to set it to `'(" ")` instead of `nil`, so the thin mode line will be shown up and it will look like an indicator for active window. Rf #18 

Also, there's another place that set `mode-line-format` to `" "`, just a few lines bellow your fix, we need to change that to `'(" ")` too.

Can you help provide a PR?

**Comment by dakling** [comment]
Sure :)
